### ISSUE TITLE
Проверить ДЗ Taxi Service

### ISSUE THREAD

**Issue by annaburnaeva** [annaburnaeva/Taxi_Service#1]
@coursar есть вопрос по данным, необходимым для выполнения операции. Переменная discount необходима мне для расчета, я инициализирую ее, присваиваю нулевое значение, потом по формуле вычисляю. Нужно ли ее в начале заносить в скобки, где необходимые данные для выполнения операции predict () , как это сделала я в своем решении?

**Comment by coursar** [comment]
Нужно было сделать так:
```java
        int discount = 0;
        if (costOfOrder > costOfOrderForDiscount) {
            discount = costOfOrder * discountPercent / 100;
            if (discount >= maxDiscount) {
                discount = maxDiscount;
            }
        }
```

Передавать в параметрах не нужно
