### ISSUE TITLE
В чём смысл присваивать переменной то же самое значение?

### ISSUE THREAD

**Issue by coursar** [annaburnaeva/Taxi_Service#3]
https://github.com/annaburnaeva/Taxi_Service/blob/3e400126e150c9ff0da0f5f354492eb06f82038b/src/main/java/TaxiService.java#L10

**Comment by annaburnaeva** [comment]
Поняла, что лишнее, логично, спасибо!

**Comment by coursar** [comment]
Зачем вы закрываете issue коммитами, которые к этому issue никакого отношения не имеют?
