### ISSUE TITLE
discount не должен передаваться в аргументах - это рассчитываемая величина

### ISSUE THREAD

**Issue by coursar** [annaburnaeva/Taxi_Service#4]
https://github.com/annaburnaeva/Taxi_Service/blob/7d3f89f351826196652423a58079f5f466e11082/src/main/java/TaxiService.java#L2-L14

И код лучше упростить вот так:

```java
     int discount = 0;
     if (costOfOrder > costOfOrderForDiscount) { 
         discount = costOfOrder * discountPercent / 100; 
         if (discount >= maxDiscount) { 
             discount = maxDiscount; 
         }
     } 
```

**Comment by annaburnaeva** [comment]
я про это как раз и спрашивала при первой сдаче задания, не смогла самостоятельно разобраться

**Comment by annaburnaeva** [comment]
Разобралась, спасибо!
